name: test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Generate Kotlin code
        run: make generate
      - name: Run tests
        run: make test
